---
runner:
  cppcheck:
    cmd: >-
      bash -o pipefail -c
      'cppcheck --enable=warning,style,performance,portability --suppress=missingIncludeSystem --template="{file}:{line}:{severity}:{message}" -i vcpkg -i vcpkg_installed -i build -i .git -i cmake-build-debug -i cmake-build-release --max-configs=1 -j 2 source/ 2>&1 | sed "s/:error:/:E:/;s/:warning:/:W:/;s/:style:/:I:/;s/:performance:/:I:/;s/:portability:/:I:/"'
    errorformat:
      - "%f:%l:%t:%m"

  xmllint:
    cmd: find data/ -name '*.xml' -exec xmllint --noout {} \;
    errorformat:
      - "%f:%l: %m"
    level: error
